Name:           perl-RRD-Simple
Version:        1.44
Release:        1%{?dist}
Summary:        Simple interface to create and store data in RRD files
License:        OSI-Approved, see LICENSE
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/RRD-Simple/
Source0:        http://www.cpan.org/authors/id/N/NI/NICOLAW/RRD-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Carp)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(RRDs)
BuildRequires:  perl(Test::Deep) >= 0.093
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod) >= 1.2
BuildRequires:  perl(Test::Pod::Coverage) >= 1.06
Requires:       perl(Carp)
Requires:       perl(File::Spec)
Requires:       perl(File::Temp)
Requires:       perl(RRDs)
Requires:       perl(Test::Deep) >= 0.093
Requires:       perl(Test::Pod) >= 1.2
Requires:       perl(Test::Pod::Coverage) >= 1.06
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
RRD::Simple provides a simple interface to RRDTool's RRDs module. This
module does not currently offer a fetch method that is available in the
RRDs module.

%prep
%setup -q -n RRD-Simple-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test || :

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes complain.txt LICENSE NOTICE README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu May 21 2015 Davide Principi <davide.principi@nethesis.it> 1.44-1
- Specfile autogenerated by cpanspec 1.78.
